### PR TITLE
Make local for local deployment

### PR DESCRIPTION
**Pull request by Yongbeom-Kim**
Now you can do make local in both frontend and backend for local deployment!

Also fixes a bug here: https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g10/actions/runs/10981720051

### CODE REVIEW

**Comment by bhnuka** [comment]
LGTM!

**Review by bhnuka — APPROVED** [review]
LGTM! Able to deploy front and back end locally.

**Review by sp4ce-cowboy — APPROVED** [review]
LGTM

**Comment by suryanshkushwaha** [comment]
Able to deploy front and back end locally.

**Pull request merged**
